### ISSUE TITLE
x permissions on binaries

### ISSUE THREAD

**Issue by dereneaton** [torognes/vsearch#65]
Not sure if this is a bug, or intentional, but the linux binaries that can be downloaded from the 'releases' link are set with only read-write privileges. Of course, it's easy to chmod this to avoid the "permission denied" error. However, since vsearch calls are sometimes embedded from within pipelines that utilize it, this error may not always be reported clearly, and for users that are not familiar with unix this can lead to a lot of confusion. It might generally be easier to release it as an executable, unless there is a reason that I don't know about why that would be a bad idea.

**Comment by torognes** [comment]
Thanks for reporting this issue. It seems like all binaries in the bin have the executable permissions on, but the files downloaded as part of the release do not have them. I think we need to put the executables in a zip or gz file to leave the executable permission on.

With the next release I think I will reorganize the repo (remove the bin, test, testbed and data folder) and make a separate compressed file for the release, containing only the binaries and the manual.

**Comment by dereneaton** [comment]
Just making a note that I had a pyrad user run into this problem again using the latest 1.1.3 download. A lot of people forget to check the permissions when sticking vsearch into a pipeline. Thanks.

**Comment by torognes** [comment]
Sorry for not fixing this issue. I plan to fix it with the next release.

**Comment by frederic-mahe** [comment]
Is this permission issue fixed in the summer branch?

**Comment by torognes** [comment]
It seems like the files distributed separately as part of the release will never have the execute bit on. I therefore plan to put the executable as well as the man file and the pdf version of the manual in a tar.gz compressed archive. Within a tar archive files may have the execute bit set. So it is not fixed yet, but will be with the next release.

The summer branch now incorporates everything in the master and dev branches. I plan to make summer the new master soon.

**Comment by torognes** [comment]
The excutable + man + pdf will then constitute a binary distribution package with the essential files. I will make two files, one for Linux and one for Mac.
